<?php
/**
 * Autoload du module HtmlTag
 * @package Common
 * @subpackage HtmlTag
 * @author Mikaël DELSOL
 * @copyright Mikaël DELSOL
 * @version 1.0
 * @date 05/11/2010
 */
require_once realpath(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'HtmlTag.inc');
require_once HTML_TAG_PHP_PATH . 'HtmlTag.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagA.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagAbbr.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagAcronym.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagAddress.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagArea.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagB.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagBase.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagBdo.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagBig.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagBlockquote.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagBody.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagBr.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagCaption.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagCite.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagCode.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagCol.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagColgroup.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagDd.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagDel.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagDfn.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagDiv.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagDl.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagDt.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagEm.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagFieldset.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagFont.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagForm.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagH.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagH1.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagH2.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagH3.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagH4.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagH5.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagH6.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagHead.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagHr.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagI.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagImg.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagInput.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagIns.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagKbd.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagLabel.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagLegend.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagLi.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagLink.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagList.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagMap.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagMeta.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagNoscript.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagObject.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagOl.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagOptgroup.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagOption.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagP.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagParam.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagPre.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagQ.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagSamp.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagScript.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagSelect.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagSmall.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagSpan.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagStrong.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagStyle.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagSub.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagSup.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagTable.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagTableCell.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagTableTPart.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagTbody.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagTd.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagTextarea.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagTfoot.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagTh.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagThead.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagTitle.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagTpl.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagTr.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagTt.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagUl.php';
require_once HTML_TAG_PHP_PATH . 'HtmlTagVar.php';
?>